### ISSUE TITLE
想自己集成一些内部部署好的模型 关键需要改动哪些地方呢

### ISSUE THREAD

**Issue by SovereignRemedy** [ninehills/llm-playground#1]
同题目，希望作者能抽出时间回复一下。多谢

**Comment by ninehills** [comment]
这个代码里的LLM是兼容 langchain的 LLM，所以你只需要实现 Langchain 的LLM 封装。

可以参考 https://github.com/ninehills/llm-playground/blob/main/wudao_llm.py
